2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_setup.py:_flush():70] Configure stats pid to 2686202
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_setup.py:_flush():70] Loading settings from /home/algo/.config/wandb/settings
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_setup.py:_flush():70] Loading settings from /home/algo/hrz/db_construct/wandb/settings
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/algo/hrz/db_construct/wandb/run-20250520_234555-h2gnbbej/logs/debug.log
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/algo/hrz/db_construct/wandb/run-20250520_234555-h2gnbbej/logs/debug-internal.log
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_init.py:init():852] calling init triggers
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'model': '/data/huangruizhi/htmlRAG/bce-reranker-base_v1', 'batch_size': 16, 'epochs': 3, 'learning_rate': 2e-05, 'max_length': 512, '_wandb': {}}
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_init.py:init():893] starting backend
2025-05-20 23:45:55,470 INFO    MainThread:2686202 [wandb_init.py:init():897] sending inform_init request
2025-05-20 23:45:55,494 INFO    MainThread:2686202 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-20 23:45:55,494 INFO    MainThread:2686202 [wandb_init.py:init():907] backend started and connected
2025-05-20 23:45:55,496 INFO    MainThread:2686202 [wandb_init.py:init():1005] updated telemetry
2025-05-20 23:45:55,520 INFO    MainThread:2686202 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-20 23:45:56,939 INFO    MainThread:2686202 [wandb_init.py:init():1104] starting run threads in backend
2025-05-20 23:45:57,069 INFO    MainThread:2686202 [wandb_run.py:_console_start():2573] atexit reg
2025-05-20 23:45:57,069 INFO    MainThread:2686202 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-20 23:45:57,070 INFO    MainThread:2686202 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-20 23:45:57,070 INFO    MainThread:2686202 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-20 23:45:57,071 INFO    MainThread:2686202 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-20 23:46:30,592 INFO    MsgRouterThr:2686202 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-20 23:46:30,880 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,881 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,882 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,882 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,882 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,882 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,883 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,883 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,883 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,883 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,884 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,884 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,884 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,884 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,884 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-20 23:46:30,884 ERROR   MainThread:2686202 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/algo/miniconda3/envs/htmlRAG/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
